services:
  db:
    image: mysql:8.3.0
    command: mysqld --default-authentication-plugin=caching_sha2_password
    restart: always
    environment:
      TZ: America/Sao_Paulo
      MYSQL_ROOT_PASSWORD: GabrielBen2024
      MYSQL_USER: ecosynergy_root
      MYSQL_PASSWORD: GabrielBen2024
      MYSQL_DATABASE: ecosynergy
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - '3308:3308'
    expose:
      - 3308
    networks:
      - ecosynergy-network
  ecosynergy-api:
    image: andersonrodriguesdev/ecosynergy-api:latest
    restart: always
    build: ./EcosynergyAPI
    working_dir: /EcosynergyAPI
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/ecosynergy?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: ecosynergy_root
      SPRING.DATASOURCE.PASSWORD: GabrielBen2024
    ports:
      - '8080:8080'
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - ecosynergy-network
networks:
  ecosynergy-network:
    driver: bridge