cors:
  originPatterns: http://localhost:8080
security:
  jwt:
    token:
      secret-key: 53cr37
      expire-length: 3600000
spring:
  application:
    name: EcosynergyAPI
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://ecosynergy-database.cz2qyuyusvdl.us-east-1.rds.amazonaws.com/ecosynergy?useLegacyDatetimeCode=false&serverTimezone=GMT%2B3
    username: admin
    password: GabrielBen123#
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: none
    show_sql: false
springdoc:
  paths-to-match: /api/**/v1/**
  swagger-ui:
    use-root-path: true